[package]
name = "gnostr-chat"
version = "0.0.2"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.1.11", features = ["derive", "env"] }
clearscreen = "3.0.0"
crossterm = { version = "0.27.0", features = ["serde"] }
duration-str = "0.9.1"
env_logger = "0.10.0"
futures = "0.3.27"
futures-timer = "3.0.2"
homedir = "0.2.1"
libp2p = { version = "0.52.3", features = ["identify", "ping", "tokio", "gossipsub", "macros", "relay", "kad", "rsa", "ed25519", "quic", "request-response", "dns", "memory-connection-limits"] }
libp2p-webrtc = { version = "0.6.0-alpha", features = ["tokio", "pem"] }
log = { version = "0.4.17", features = ["kv"] }
rand = "0.8.5"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0.59"
tokio = { version = "1.27.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
tui = { version = "0.14", default-features = false, features = ['crossterm', 'serde'] }
