name: Continuous Integration

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: '-Dwarnings' # Never tolerate warnings.
    defaults:
      run:
        working-directory: ./chat
    steps:
      - uses: actions/checkout@v3
        with:
          depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        if: ${{ !env.ACT }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo fmt -- --check
      - run: cargo clippy
      - run: cargo test
  go-check:
    uses: libp2p/uci/.github/workflows/go-check.yml@v0.0
    with:
      go-version: '1.21.x'
  go-test:
    uses: libp2p/uci/.github/workflows/go-test.yml@v0.0
    with:
      go-versions: '["1.21.x"]'
